### ISSUE TITLE
SSL Support

### ISSUE THREAD

**Issue by JadoJodo** [mikecrittenden/duckduckgoog#10]
Any chance DDG can be updated w/ SSL support? Perhaps using https://www.npmjs.com/package/letsencrypt-express?

**Comment by mikecrittenden** [comment]
Done: https://www.duckduckgoog.com/

**Comment by JadoJodo** [comment]
Can you add a redirect to https from http?

**Comment by TPS** [comment]
@mikecrittenden This doesn't work anymore, it seems, especially when using https://www.duckduckgoog.com/?q=%s syntax; it just redirects to unencrypted.  Can you take a look?
